on:
  pull_request

jobs:
  code-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Code Standards Test
        uses: docker://aligent/code-standards-pipe-php:7.4-experimental
        env:
          STANDARDS: "Magento2"
          SKIP_DEPENDENCIES: "true"

