on:
  push

jobs:
  code-standards:
    steps:
      - name: Code Standards Test
        uses: docker://aligent/code-standards-pipe-php:7.4-experimental
        env:
          STANDARDS: "Magento2"
          SKIP_DEPENDENCIES: "true"

